language: java
sudo: false # faster builds
install: mvn clean dependency:resolve
script: mvn install -P eclipse,fresch

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 096c9f99-8956-4429-84af-c12f09980218
