package cz.encircled.joiner.core.hibernate;

import cz.encircled.joiner.core.MultipleMappingsForSameClassOnSingleEntityTest;

public class HibernateMultipleMappingsForSameClassOnSingleEntityTest extends MultipleMappingsForSameClassOnSingleEntityTest {
}
